INSERT INTO STUDENT(ID, NAME, STREET, TOWN)
values(1, 'naam1', 'straat1', 'town1');
INSERT INTO APARTMENT(ID, ADDRESS, LOCATION, PRICE, BATHROOM_PRESENT, KITCHEN_PRESENT)
values(1,'testAdress1', 'testLocation1', 200, true, true);
INSERT INTO APARTMENT(ID, ADDRESS, LOCATION, PRICE, BATHROOM_PRESENT, KITCHEN_PRESENT)
values(2,'testAdress2', 'testLocation2', 300, true, true);
INSERT INTO APARTMENT(ID, ADDRESS, LOCATION, PRICE, BATHROOM_PRESENT, KITCHEN_PRESENT)
values(3,'testAdress3', 'testLocation3', 400, true, true);
